// src/view/userManage/index.vue
<template>
    <div class="toolbar">
        <div class="left-part">
            <el-button  type="primary" @click="showDialog('add')">新增后台用户</el-button>
            <el-button  type="primary">导出</el-button>
        </div>
        <div class="right-part">
            <el-input
                v-model="user_name"
                :clearable="true"
                style="width: 240px"
                placeholder="请输入用户名"
                @keyup.enter="getData"
                @clear="getData">
                <template #append>
                    <el-button @click="getData" :icon="Search" />
                </template>
            </el-input>
        </div>
    </div>
    <div>
        <zt-table 
            :loading="loading"
            :data="userList"
            :pagination="pagination"
            @handleSizeChange="handleSizeChange"
            @handleCurrentChange="handleCurrentChange">
            <el-table-column
                v-for="item in columns"
                :key="item.key"
                :prop="item.key"
                :label="item.title">
                <template #default="{row}">
                    <span>{{ item.show ? item.show(row[item.key]) || '--' : row[item.key] || '--' }}</span>
                </template>
            </el-table-column>
            <el-table-column
                    fixed="right"
                    prop="action"
                    label="操作"
                    width="300">
                <template #default="{row}">
                    <el-button text type="primary" @click="showDialog('modify', row.id)">
                        编辑
                    </el-button>
                    <el-button text type="primary" @click="resetPassword(row.id)">
                        重置密码
                    </el-button>
                    <el-popconfirm v-if="row.role_level > 1"  title="确认删除该用户？" @confirm="delUser(row.id)">
                        <template #reference>
                            <el-button text type="danger">
                                删除
                            </el-button>
                        </template>
                    </el-popconfirm>
                </template>
            </el-table-column>
        </zt-table>
    </div>
    <user-info-dialog 
        v-if="isShow" 
        ref="userDialog"
        :user-id="userId" 
        :is-edit="isEdit" 
        :role-list="roleList.filter((item: any) => item.role_name !== '超级管理员')"
        @isShowFalse="isShowFalse"
        @getData="getData">
    </user-info-dialog>
    <modify-pw-dialog :is-show="modifyPw" @closeDialog="closeDialog"></modify-pw-dialog>
</template>

<script setup lang="ts">
    import { ref, getCurrentInstance, onMounted, nextTick } from 'vue'
    import { Search } from '@element-plus/icons-vue'
    import modifyPwDialog from './components/modifyPwDialog.vue'
    import userInfoDialog from './components/userInfoDialog.vue'
    import { formatDate } from '@/utils';
    import { paginationType } from '@/type/common';

    const { proxy }: any = getCurrentInstance() 
    const $api = proxy.$api
    const $success = proxy.$success
    const $error = proxy.$error

    const columns = [
            {
                title: "用户名",
                key: "user_name",
            },
            {
                title: '用户等级',
                key: 'role_level',
                show: (val: number) => {
                    if (!Array.isArray(roleList.value) || !roleList.value) return
                    return roleList.value.find((item: any) => item.role_level === val).role_name
                }
            },
            {
                title: "创建时间",
                key: "create_time",
                show: (date: Date) => {
                    return formatDate(date, 'yyyy-MM-dd hh:mm:ss')
                }
            },
            {
                title: "更新时间",
                key: "update_time",
                show: (date: Date) => {
                    return formatDate(date, 'yyyy-MM-dd hh:mm:ss')
                }
            }
    ]
    const pagination = ref<paginationType>({
        current: 1,
        size: 10,
        count: 0
    })
    const user_name = ref<string>('')
    const userDialog = ref<any>()
    const userId = ref<number>(-1)
    let loading = ref(false)
    let userList = ref([])
    let roleList = ref<any>([])
    // 修改密码弹出框
    let modifyPw = ref(false)
    let isShow = ref(false)
    let isEdit = ref(false)
    const closeDialog = (val: string) => {
        switch (val) {
            case 'modifyPw':
                modifyPw.value = false
                break;
            default:
                isShow.value = false
                break;
        }
    }
    const showDialog = (val: string, id: number = -1) => {
        isShow.value = true
        if (val === 'modify') {
            isEdit.value = true
        }
        userId.value = id
        nextTick(() => {
            userDialog.value.showDialog()
        })
    }
    const isShowFalse = () => {
        isShow.value = false
    }
    const getData = async () => {
        loading.value = true
        const params: any = {
            page: pagination.value.current,
            size: pagination.value.size
        }
        if (user_name.value) {
            params.user_name = user_name.value
        }
        try {
            const res = await $api.User.getData(params)
            if (res.result) {
                userList.value = res.data
                pagination.value.count = res.count
                loading.value = false
            }
        } catch (error) {
            
        }
    }
    const handleSizeChange = (size: number) => {
        pagination.value.current = 1
        pagination.value.size = size
        getData()
    }
    const handleCurrentChange = (page: number) => {
        pagination.value.current = page
        getData()
    }
    const getRoleList = async () => {
        try {
            const res = await $api.Role.getRoleList()
            if (res.result) {
                roleList.value = res.data
            }
        } catch (error) {
            
        }
    }
    const delUser = async (id: number) => {
        try {
            const res = await $api.User.delUser(id)
            if (res.result) {
                $success(res.message)
                getData()
            } else {
                $error('删除失败')
            }
        } catch(error) {
            console.log(error)
        }
    }
    
    const resetPassword = (id: number) => {
        $api.User.resetPassword(id).then((res: any) => {
            if (res.result) {
                $success('重置成功')
            }
        })
    }
    onMounted(() => {
        getRoleList()
        getData()
    })
</script>

<style lang="scss" scoped>
    .toolbar{
        display: flex;
        box-sizing: border-box;
        justify-content: space-between;
        align-items: center;
        height: 60px;
        background: #fff;
        padding: 20px;
        margin-bottom: 10px;
    }
</style>

// src/pages/userManage/index.tsx
import React, { useEffect, useState } from "react"
import { useOutletContext } from "react-router-dom"
import { Space, Table, Button, Select, Input, Spin, message } from "antd"
import { SearchOutlined } from '@ant-design/icons'
import type { TableProps } from "antd"
import { roleType, userType } from "@/type/userType"
import $request from '@/api/api'
import './index.scss'
import UserDialog from "./userDialog"

const UserManage: React.FC = () => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const [globalUserInfo, _] = useOutletContext<any>()
    const [searchValue, setSearchValue] = useState('')
    const [selectValue, setSelectValue] = useState('')
    const [isLoading, setIsLoading] = useState<boolean>(false)
    const [roleList, setRoleList] = useState<Array<roleType>>([])
    const [tableData, setTableData] = useState<Array<userType>>([])
    const [userInfo, setUserInfo] = useState<userType>({
        user_name: '',
        organization: ''
    })
    // 不能写死pageSize
    const [paginationProp, setPaginationProp] = useState({
        current: 1,
        pageSizeOptions: [10, 20, 50],
		defaultPageSize: 10,
        showSizeChanger: true,
        total: 0,
        onChange: (page: number, pageSize: number) => {
            changePage(page, pageSize)
        }
    })
    const columns: TableProps<userType>['columns'] = [
        {
            title: "用户名",
            key: "user_name",
            dataIndex: 'user_name',
            render: (_, record) => (
                record.user_name || '--'
            )
        },
        {
            title: '所在区域',
            key: 'area_name',
            dataIndex: 'area_name',
            render: (_, record) => (
                record.area_name || '--'
            )
        },
        {
            title: '隶属商户',
            key: 'merchant_name',
            dataIndex: 'merchant_name',
            render: (_, record) => (
                record.merchant_name || '--'
            )
        },
        {
            title: '用户角色',
            key: 'role_name',
            dataIndex: 'role_name',
            render: (_, record) => (
                record.role_name || '--'
            )
        },
        {
            title: '描述',
            key: 'desc',
            dataIndex: 'desc',
            render: (_, record) => (
                record.desc || '--'
            )
        },
        {
            title: "创建时间",
            key: "create_time",
            dataIndex: "create_time",
            render: (_, record) => (
                record.create_time|| '--'
            )
        },
        {
            title: "更新时间",
            dataIndex: "update_time",
            key: "update_time",
            render: (_, record) => (
                record.update_time || '--'
            )
        },
        {
            title: '操作',
            key: 'action',
            render: (_, record) => (
                <Space size="middle">
                    {/* record：表格上的数据 */}
                    <Button type="link" onClick={() => { setIsEdit(true); setIsShow(true); setUserInfo(record) }}>编辑</Button>
                    <Button danger type="text" onClick={() => {delUser(record.id)}}>删除</Button>
                    <Button danger type="text" onClick={() => {resetPassword(record.id)}}>重置密码</Button>
                </Space>
            ),
        }
    ]
    const [isShow, setIsShow] = useState<Boolean>(false)
    const [isEdit, setIsEdit] = useState<Boolean>(false)

    const changePage = (page: number, pageSize: number) => {
		const current = pageSize === paginationProp.defaultPageSize ? page : 1
        setPaginationProp({
            ...paginationProp,
			current,
			defaultPageSize: pageSize
        })
        getTableData({ page: current, size: pageSize})
    }
    const selectChange = (value: string) => {
        setSelectValue(value)
    }
    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { value: inputValue } = e.target
        setSearchValue(inputValue)
    }
    const handleShow = (val: Boolean) => {
        setIsShow(val)
        setIsEdit(false)
        getTableData()
    }
    const getTableData = async (exact: Object = {}) => {
        setIsLoading(true)
        try {
            const params = {
                page: paginationProp.current,
                size: paginationProp.defaultPageSize,
                area_id: globalUserInfo.area_id,
                ...exact
            }
            const res = await $request.User.getUserList(params)
            if (res.result) {
                setTableData([...res.data])
                setIsLoading(false)
                setPaginationProp({
                    ...paginationProp,
                    total: res.count
                })
            }
        } catch (error) {
            console.log(error)
        }
    }
    const getRoleList = async () => {
        try {
            const res = await $request.Role.getRoleList({ size: -1 })
            if (res.result) {
                setRoleList(res.data.map((item: roleType) => {
                    return {
                        ...item,
                        value: item.role_level,
                        label: item.role_name
                    }
                }))
            }
        } catch (error) {
            console.log(error)
        }
    }
    const delUser = async (id: Number) => {
        try {
            const res = await $request.User.delUser(id)
            if (res.result) {
                message.success('删除成功')
                getTableData()
            }
        } catch (error) {
            console.log(error)
        }
    }
    const resetPassword = async (id: Number) => {
        try {
            const res = await $request.User.resetPassword(id)
            if (res.result) {
                message.success('重置成功')
            }
        } catch (error) {
            console.log(error)
        }
    }
    useEffect(() => {
        getRoleList()
        getTableData()
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])
    return (
        <div id="user-manage">
            <div className="search-area">
                <div className="left-part">
                    <Button type="primary" onClick={() => { setIsShow(true) }}>新增用户</Button>
                </div>
                <div className="right-part">
                    <Select
                        allowClear
                        style={{ width: 200 }}
                        placeholder="请选择角色类型"
                        onChange={selectChange}
                        options={roleList}
                    />
                    <Input
                        onChange={handleChange}
                        style={{ width: 300 + 'px', marginLeft: 10 + 'px', marginRight: 10 + 'px' }}
                        placeholder="请输入用户名进行搜索"
                        onKeyDown={(event) => { event.keyCode === 13 && getTableData({ user_name: searchValue, role_level: selectValue }) }}>
                    </Input>
                    <Button
                        type="primary"
                        icon={<SearchOutlined />}
                        onClick={() => { getTableData({ user_name: searchValue, role_level: selectValue }) }}>
                        搜索
                    </Button>
                </div>
            </div>
            {/* position属性不能直接在变量里配置 */}
            <Spin spinning={isLoading}>
                <Table columns={columns} dataSource={tableData} pagination={{ ...paginationProp, position: ['bottomLeft'] }} />
            </Spin>
            <UserDialog isShow={isShow} isEdit={isEdit} userInfo={userInfo} handleShow={handleShow}></UserDialog>
        </div>
    )
}

export default UserManage
